### PR TITLE
Added ability for fluid to roll down sloped objects

### PR DESCRIPTION
**Pull request by Wully616**
I fixed some spelling of Botle > Bottle
I added the ability for objects to block the liquid pouring down, if something is in the way it will calculate the slope of the blocking object, find the edge the liquid would pour from and continue pouring down from there, an example can be seen here in the demo I added to the example scene
https://gyazo.com/0c8268bade1fa2d0c579548b625b256e

### CODE REVIEW

**Comment by Macoron** [comment]
Hey @Wully616, thank you for your contribution to project. Here is what I have found so far:

1. Right now there are missing links in materials and prefab in examples scene
Screen
2. When you fixed typo in bottleneckRadius - all prefabs and scenes values got default bottleneckRadius to 0.1. Check the red sphere here:
image
3. Variable raycastHit is public and exposed in inspector. I think it would be better to make it private.

**Comment by Wully616** [comment]
Hey!
Sorry about that, I didn't notice it reset the value on the prefabs.
I changed the raycastHit variable to private.
I reverted changes to the scene and remade a simpler example showing objects blocking the liquid.
https://imgur.com/a/RdoStLk

**Comment by Macoron** [comment]
Hey Wully616, slope logic looks amazing. Great work!

However, I'm a bit concern about two things:
1. It's endless. Maybe add some distance limit like this?
` var hitDist = Vector3.Distance(revHit.point, hit.point);`
`if (hitDist > maxSlopeDistance) break;`
2. It's recursive. I guess, it won't be a big problem for performance if there are distance limit.

**Comment by Wully616** [comment]
Hey!

It is endless, adding in a distance limit makes sense, or X number of slopes can be traversed, i'll have a look at this today or tomorrow.

The illusion is somewhat broken by the particles not existing long enough, or if they bounce or fly off the edge of a slope, the slope logic doesnt take into account any sort of velocity of the liquid and just drops the liquid straight down.

Any idea on how to make the particle effects match the sloping logic? I'm not very experienced with particles. Naively I thought of just spawning another particle system at each edge point of the slope.

**Comment by Macoron** [comment]
You can just change prefab particles lifetime here. It will hit performance a bit, but not much.
image

Also dampen works kinda like friction. It will slow down particles.
image

**Comment by Wully616** [comment]
Hey!

I added in a integer limit check on the number of objects it can hit rather than a distance check. Though it wouldn't be impossible to also put in a distance check as well.

I've realised there is a bug in how I do the raycasting to find where the edges are, its not big enough. 

I tried extending out the raycast based on the bounds box of the collider, which fixes it however I think I know how to figure out where the edge of the box is without using a raycast at all.

By just using the vectors, since I know the slope on the box and I can figure out the distance from the liquid hitpoint on the box to the bounds of the box collider, I should be able to figure out exactly where the edge is.

**Comment by Macoron** [comment]
Hey @Wully616 ,

The idea about bounds sounds great. You can make second pull request, but please check-out from master before. I changed example scene and code styling a bit.

Recently I found out about [OnParticleCollision](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnParticleCollision.html). It may help you simulate much complex behavior for liquid drops.

**Comment by Wully616** [comment]
Hey @Macoron 
Sure I'll do that, no problem. Just be aware there is a bug with the raycasting edge right now if the box is too big the raycast doesnt start far enough away. But I could make a pull request with a hotfix tonight while I figure out the bounds idea.

I seen that about the OnParticleCollision, it would make it much more realistic but I'm not sure how performance would be. It would be good to test that and perhaps add it as an alternative option to the simple liquid motion

**Pull request merged**
